Document: cegui
Title: Debian cegui Manual
Author: <insert document author here>
Abstract: This manual describes what cegui is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cegui/cegui.sgml.gz

Format: postscript
Files: /usr/share/doc/cegui/cegui.ps.gz

Format: text
Files: /usr/share/doc/cegui/cegui.text.gz

Format: HTML
Index: /usr/share/doc/cegui/html/index.html
Files: /usr/share/doc/cegui/html/*.html
